### ISSUE TITLE
To-do: 8/6

### ISSUE THREAD

**Issue by chris8736** [chris8736/tft-ai#1]
- [ ] complete board tracking and full range of movement
- [ ] verify successful selling, implement team building
- [ ] track stage, gold, and xp
- [ ] implement interest penalty and star distribution to value function
